import React, { useState } from 'react';
import { X, Copy, Check, Database, ExternalLink, RefreshCw, Key, ShieldCheck, Terminal } from 'lucide-react';
import { supabaseUrl, supabaseAnonKey, isSupabaseConfigured, setCustomSupabaseCredentials } from '../lib/supabase';
import { resetDemoData } from '../services/productService';

interface SupabaseModalProps {
  isOpen: boolean;
  onClose: () => void;
  onResetProducts: () => void;
}

const SCHEMA_SQL = `-- 1. Create Products Table for Atelier Store
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
  stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  image_url TEXT NOT NULL,
  category TEXT NOT NULL,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 3. Allow Public Read & Demo Operations
CREATE POLICY "Public products viewable" ON products FOR SELECT USING (true);
CREATE POLICY "Public products insert" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Public products update" ON products FOR UPDATE USING (true);
CREATE POLICY "Public products delete" ON products FOR DELETE USING (true);

-- 4. Curated Catalog Seed Data (18 Items)
INSERT INTO products (title, description, price, stock_quantity, image_url, category, is_featured)
VALUES
  ('Kinto Ceramic Pour-Over Mug', 'Artisanal stoneware mug with a tactile matte glaze and raw unglazed terracotta foot.', 36.00, 14, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=900&auto=format&fit=crop&q=80', 'objects', true),
  ('Machined Solid Brass Catchall', 'Precision milled from a solid billet of untreated architectural brass.', 68.00, 12, 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=900&auto=format&fit=crop&q=80', 'objects', true),
  ('Matte Black Cold-Drip Brewer', 'Slow-extraction borosilicate glass cold brew tower with micro-etched stainless steel filter.', 145.00, 8, 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=900&auto=format&fit=crop&q=80', 'objects', true),
  ('Anodized Aluminum Table Clock', 'Silent sweep quartz movement housed within a cylindrical brushed aluminum chassis.', 85.00, 16, 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?w=900&auto=format&fit=crop&q=80', 'objects', false),
  ('Minimalist Beechwood Bookstand', 'Single-piece steam-bent solid European beechwood stand with hand-rubbed organic oil finish.', 54.00, 22, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=900&auto=format&fit=crop&q=80', 'objects', false),
  ('Woven European Linen Overshirt', 'Tailored from heavyweight organic French flax linen with horn-style buttons.', 128.00, 9, 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=900&auto=format&fit=crop&q=80', 'apparel', true),
  ('Heavyweight Ribbed Cotton Beanie', 'Knitted from dry-spun combed carded cotton yarns in a traditional fisherman 7-gauge stitch.', 44.00, 15, 'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=900&auto=format&fit=crop&q=80', 'apparel', false),
  ('Raw Selvedge Denim Chore Coat', 'Constructed from 13.5oz shuttle-loom Japanese selvedge denim with triple needle stitching.', 195.00, 7, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&auto=format&fit=crop&q=80', 'apparel', true),
  ('Supima Cotton Heavy Pocket Tee', 'Knit from long-staple combed Supima cotton with reinforced ribbed collar.', 48.00, 35, 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=900&auto=format&fit=crop&q=80', 'apparel', false),
  ('Merino Wool Waffle Knit Crewneck', 'Spun from extra-fine 19.5 micron Australian merino wool in thermal waffle stitch.', 165.00, 11, 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=900&auto=format&fit=crop&q=80', 'apparel', true),
  ('Archival Grid Journal No. 4', 'Thread-sewn layflat binding filled with 160 pages of 120gsm fountain-pen friendly paper.', 24.00, 28, 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=900&auto=format&fit=crop&q=80', 'stationery', false),
  ('Brushed Titanium Fountain Pen', 'CNC turned aerospace-grade titanium with an iridium-tipped German steel nib.', 88.00, 6, 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=900&auto=format&fit=crop&q=80', 'stationery', true),
  ('Solid Brass Architect Ruler 30cm', 'Metric and imperial graduated edges laser etched into raw untreated architectural brass.', 32.00, 19, 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=900&auto=format&fit=crop&q=80', 'stationery', false),
  ('Vegetable-Tanned Leather Pen Sleeve', 'Hand-stitched Tuscan vegetable-tanned bridle leather with beeswax burnished edges.', 42.00, 14, 'https://images.unsplash.com/photo-1585336261026-7782b5f7936a?w=900&auto=format&fit=crop&q=80', 'stationery', false),
  ('Hinoki Cypress Room Diffuser', 'Cold-pressed wild hinoki wood essential oil in apothecary amber glass jar.', 52.00, 18, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=900&auto=format&fit=crop&q=80', 'living', true),
  ('Cast Iron Incense Burner Bowl', 'Traditional Nambu Tekki sand-cast iron vessel with removable brass pinholder.', 48.00, 11, 'https://images.unsplash.com/photo-1602928321679-560bb453f190?w=900&auto=format&fit=crop&q=80', 'living', false),
  ('Hand-Poured Smoked Cedar Candle', '100% domestic soy wax scented with charred atlas cedar, patchouli, and crackling wood wick.', 34.00, 25, 'https://images.unsplash.com/photo-1596433809252-260c2745dfdd?w=900&auto=format&fit=crop&q=80', 'living', false),
  ('Belgian Washed Linen Throw Blanket', 'Stonewashed master flax linen woven in a subtle herringbone pattern with eyelash fringe.', 135.00, 10, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=900&auto=format&fit=crop&q=80', 'living', true);`;

export const SupabaseModal: React.FC<SupabaseModalProps> = ({
  isOpen,
  onClose,
  onResetProducts,
}) => {
  const [activeTab, setActiveTab] = useState<'status' | 'sql' | 'steps'>('status');
  const [inputUrl, setInputUrl] = useState(supabaseUrl);
  const [inputKey, setInputKey] = useState(supabaseAnonKey);
  const [copied, setCopied] = useState(false);
  const [saveStatus, setSaveStatus] = useState<string | null>(null);

  if (!isOpen) return null;

  const handleCopySql = async () => {
    try {
      await navigator.clipboard.writeText(SCHEMA_SQL);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
    }
  };

  const handleSaveCredentials = (e: React.FormEvent) => {
    e.preventDefault();
    setCustomSupabaseCredentials(inputUrl, inputKey);
    setSaveStatus('Credentials saved! Reloading connection...');
  };

  const handleClearCredentials = () => {
    setCustomSupabaseCredentials('', '');
    setInputUrl('');
    setInputKey('');
    setSaveStatus('Cleared custom credentials.');
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-stone-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="relative bg-white border border-stone-300 w-full max-w-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-stone-200">
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5 text-stone-900" />
            <div>
              <h2 className="font-serif text-lg text-stone-900 font-medium">
                Supabase Backend & SQL Configuration
              </h2>
              <p className="text-xs text-stone-500 font-mono">
                PostgreSQL Schema • Environment Keys • Live Sync
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-stone-400 hover:text-stone-700 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Navigation */}
        <div className="flex border-b border-stone-200 bg-stone-50 px-6 gap-6 text-xs font-mono">
          <button
            onClick={() => setActiveTab('status')}
            className={`py-3 border-b-2 transition-colors cursor-pointer uppercase tracking-wider ${
              activeTab === 'status'
                ? 'border-stone-900 text-stone-900 font-semibold'
                : 'border-transparent text-stone-500 hover:text-stone-800'
            }`}
          >
            1. Connection Status
          </button>
          <button
            onClick={() => setActiveTab('sql')}
            className={`py-3 border-b-2 transition-colors cursor-pointer uppercase tracking-wider ${
              activeTab === 'sql'
                ? 'border-stone-900 text-stone-900 font-semibold'
                : 'border-transparent text-stone-500 hover:text-stone-800'
            }`}
          >
            2. SQL Schema Script
          </button>
          <button
            onClick={() => setActiveTab('steps')}
            className={`py-3 border-b-2 transition-colors cursor-pointer uppercase tracking-wider ${
              activeTab === 'steps'
                ? 'border-stone-900 text-stone-900 font-semibold'
                : 'border-transparent text-stone-500 hover:text-stone-800'
            }`}
          >
            3. Setup Steps
          </button>
        </div>

        {/* Tab Content */}
        <div className="p-6 max-h-[70vh] overflow-y-auto">
          {activeTab === 'status' && (
            <div className="space-y-6">
              {/* Status Banner */}
              <div
                className={`p-4 border text-xs flex items-start gap-3 ${
                  isSupabaseConfigured
                    ? 'bg-emerald-50/70 border-emerald-300 text-emerald-900'
                    : 'bg-stone-100 border-stone-300 text-stone-800'
                }`}
              >
                <div className="mt-0.5">
                  <div
                    className={`w-2.5 h-2.5 rounded-full ${
                      isSupabaseConfigured ? 'bg-emerald-600 animate-pulse' : 'bg-stone-500'
                    }`}
                  ></div>
                </div>
                <div>
                  <h3 className="font-semibold font-mono uppercase tracking-wider">
                    {isSupabaseConfigured
                      ? 'Connected to Live Supabase Postgres'
                      : 'Active Mode: Autonomous Local Persistence'}
                  </h3>
                  <p className="mt-1 leading-relaxed text-stone-600 font-light">
                    {isSupabaseConfigured
                      ? `All CRUD operations (create, update, delete, stock tracking) are synchronizing directly with your Supabase database.`
                      : `The website currently uses a fully functional local persistence engine so you can test all CRUD features, add items, edit prices, and order products right now without waiting for external API setup.`}
                  </p>
                </div>
              </div>

              {/* Form to provide Supabase keys directly in UI */}
              <form onSubmit={handleSaveCredentials} className="space-y-4">
                <div>
                  <h3 className="text-xs font-mono uppercase tracking-wider text-stone-900 font-semibold mb-1">
                    Connect Your Supabase Project Credentials
                  </h3>
                  <p className="text-xs text-stone-500 font-light leading-relaxed">
                    You can either add these into your <code className="bg-stone-100 px-1 py-0.5 border">.env.local</code> file or input them below to link live Supabase tables instantly.
                  </p>
                </div>

                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-stone-600 mb-1">
                    Project URL (VITE_SUPABASE_URL)
                  </label>
                  <input
                    type="url"
                    value={inputUrl}
                    onChange={(e) => setInputUrl(e.target.value)}
                    placeholder="https://xyzcompany.supabase.co"
                    className="w-full px-3 py-2 text-xs font-mono border border-stone-300 focus:outline-none focus:border-stone-800 bg-stone-50/50"
                  />
                </div>

                <div>
                  <label className="block text-xs font-mono uppercase tracking-wider text-stone-600 mb-1">
                    Anon Public API Key (VITE_SUPABASE_ANON_KEY)
                  </label>
                  <input
                    type="password"
                    value={inputKey}
                    onChange={(e) => setInputKey(e.target.value)}
                    placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    className="w-full px-3 py-2 text-xs font-mono border border-stone-300 focus:outline-none focus:border-stone-800 bg-stone-50/50"
                  />
                </div>

                {saveStatus && (
                  <p className="text-xs text-emerald-700 font-mono">{saveStatus}</p>
                )}

                <div className="flex items-center justify-between pt-2">
                  <button
                    type="button"
                    onClick={handleClearCredentials}
                    className="text-xs text-stone-500 hover:text-stone-800 underline underline-offset-4"
                  >
                    Reset to Local Mode
                  </button>
                  <button
                    type="submit"
                    className="px-5 py-2 text-xs font-mono uppercase tracking-wider bg-stone-900 text-stone-50 hover:bg-stone-800 transition-colors cursor-pointer"
                  >
                    Apply & Connect
                  </button>
                </div>
              </form>

              {/* Reset seed products option */}
              <div className="pt-4 border-t border-stone-200 flex items-center justify-between text-xs text-stone-500">
                <span>Need to restore default product catalogue?</span>
                <button
                  onClick={() => {
                    resetDemoData();
                    onResetProducts();
                    setSaveStatus('Default products restored.');
                  }}
                  className="flex items-center gap-1 text-stone-700 hover:text-stone-900 font-mono underline"
                >
                  <RefreshCw className="w-3 h-3" />
                  <span>Restore Seed Data</span>
                </button>
              </div>
            </div>
          )}

          {activeTab === 'sql' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-mono text-xs uppercase tracking-wider text-stone-900 font-semibold">
                    PostgreSQL Migration Script
                  </h3>
                  <p className="text-xs text-stone-500">
                    Run this once in your Supabase SQL Editor.
                  </p>
                </div>
                <button
                  onClick={handleCopySql}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono uppercase tracking-wider bg-stone-900 text-white hover:bg-stone-800 transition-colors"
                >
                  {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy SQL'}</span>
                </button>
              </div>

              <pre className="p-4 bg-stone-900 text-stone-100 font-mono text-xs overflow-x-auto rounded-none leading-relaxed border border-stone-700">
                {SCHEMA_SQL}
              </pre>
            </div>
          )}

          {activeTab === 'steps' && (
            <div className="space-y-4 text-xs text-stone-700 leading-relaxed font-light">
              <h3 className="font-mono uppercase tracking-wider text-stone-900 font-semibold">
                How to Connect with Supabase:
              </h3>
              <ol className="list-decimal pl-5 space-y-2">
                <li>
                  Go to <a href="https://supabase.com" target="_blank" rel="noreferrer" className="text-stone-900 font-medium underline">supabase.com</a> and create a new project.
                </li>
                <li>
                  Open the <strong>SQL Editor</strong> in your Supabase sidebar and paste the SQL script from Tab 2, then click <strong>Run</strong>.
                </li>
                <li>
                  Go to <strong>Project Settings</strong> → <strong>API</strong>. Copy your <strong>Project URL</strong> and <strong>anon public key</strong>.
                </li>
                <li>
                  Paste them into Tab 1 of this modal (or in your <code className="bg-stone-100 px-1 py-0.5">.env.local</code> file as <code className="bg-stone-100 px-1 py-0.5">VITE_SUPABASE_URL</code> and <code className="bg-stone-100 px-1 py-0.5">VITE_SUPABASE_ANON_KEY</code>).
                </li>
                <li>
                  All product creations, edits, inventory deductions, and deletions will persist live in your PostgreSQL cloud database.
                </li>
              </ol>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
